project:
  type: website
  output-dir: docs

website:
  title: "Simple Learning Journey"
  navbar:
    right:
      - about.qmd
      - projects.qmd
      - icon: github
        href: https://github.com/SamithVa
      - icon: twitter
        href: https://twitter.com
  page-footer: |
    This page is made using [Quarto](https://quarto.org)


format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css



