project:
  type: website
  output-dir: docs

website:
  title: "A Simple Journey"
  navbar:
    right:
      - text: "About"
        menu: 
          - text: "English"
            href: about-en.qmd
          - text: "Chinese"
            href: about-cn.qmd
        
      - text: Projects 
        href: projects.qmd
      - icon: github
        href: https://github.com/SamithVa
      # - icon: twitter
      #   href: https://twitter.com
  page-footer: |
    This page is made using [Quarto](https://quarto.org)


format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css



