--- 
title: "Regression and Classification"
author: "Samith Va"
date: "2024-03-29"
categories: [deep learning]
toc : true
---

# Linear Regression 

Linear regression is a statistical method used to model the relationship between a dependent variable and one or more independent variables. It assumes that there is a **linear relationship** between the independent variables (predictors) and the dependent variable (outcome).

## Loss Function

With linear regression model, we generally use **Square-Error** as the loss function.

$$L(f) = \frac{1}{2}\sum_{i=1}^{n}(f(x^{(i)}) - y^{(i)})^2$$

Where the superscipt $i$ denotes $i^{\text{th}}$ data in the dataset

## Learning Rate

**Learning rate (lr)**  is the rate that weight is updated in order to reduce the loss. If lr is too large, the model might not able to find optima weight with smallest loss. On the other hand if lr is too small, the model weight will be updated very slow, which lead in needing more iterations to find the optima weight. 

How to choose the optimal lr ? 
: We can change lr with number of iterations. Suppose that we are at $t$ iteration and learning rate $\alpha$ :

$$ \alpha_t = \frac{\alpha}{\sqrt{t + 1}}$$



1. What is the best learning rate ? 

